# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Karl"
email = "karl@stonkmarket.de"
link = "https://github.com/StasonJatham"
avatar = "/karl_square_yellow_back.jpeg"
about_me = "Ich bin Karl und teile mein persÃ¶nliches Investment-Tagebuch, um anderen zu helfen, ihr Wissen Ã¼ber das Investieren zu erweitern. Neben meinen finanziellen Interessen genieÃŸe ich GamingğŸ®, BouldernğŸª¨, WandernğŸ¥¾ und PizzağŸ•. Ich bin aufgeschlossen und immer bereit, neue Dinge auszuprobieren."
