# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Karl"
email = "karl@stonkmarket.de"
link = "https://github.com/StasonJatham"
avatar = "/karl_square_yellow_back.jpeg"
about_me = "Hallo! Ich bin Karl. Ich investiere seit ich 18 bin und mÃ¶chte von jetzt an mein investemnt Tagebuch Ã¶ffentlich fÃ¼hren. Ich schreibe hier darÃ¼ber warum ich Aktien kaufe und verkaufe. Das ganze ist nicht als Empfehlung zu verstehen, es ist nur mein persÃ¶nliches Investment Tagebuch. Ansonsten mag ich gamingğŸ®, bouldernğŸª¨, wandernğŸ¥¾ und pizzağŸ•."
