# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#menu-advanced-configuration
# -------------------------------------------------------------------------------------

[[main]]
  identifier = "posts"
  # you can add extra information before the name (HTML format is supported), such as icons
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  name = "ğŸ“Artikel"
  url = "/posts/"
  # title will be shown when you hover on this menu link
  title = ""
  weight = 1
  # FixIt 0.2.14 | NEW add user-defined content to menu items
  [main.params]
    # add css class to a specific menu item
    class = ""
    # whether set as a draft menu item whose function is similar to a draft post/page
    draft = false
    # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
    #icon = "fa-solid fa-archive"
    # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
    type = ""

[[main]]
  identifier = "kategorien"
  pre = ""
  post = ""
  name = "ğŸ—ƒKategorien"
  url = "/categories/"
  title = ""
  weight = 3
  [main.params]
    #icon = "fa-solid fa-th"

[[main]]
  identifier = "contact"
  pre = ""
  post = ""
  name = "ğŸ›¸Kontakt"
  url = "/contact/"
  title = ""
  weight = 4
  [main.params]

[[main]]
  identifier = "support"
  pre = ""
  post = ""
  name = "ğŸ’µSupport"
  url = "/support/"
  title = ""
  weight = 5
  [main.params]

[[main]]
  identifier = "dips"
  pre = ""
  post = ""
  name = "ğŸ“‰Dips"
  url = "/dips/"
  title = ""
  weight = 5
  [main.params]
    #icon = "fa-solid fa-th"
